xastropy/xastropy

- xastropy/xguis/spec_guis.py
> fixed XSpectru1D

- docs/examples/XFitLLSGUI.ipynb
- docs/examples/xspec_doc.ipynb
- xastropy/xguis/spec_guis.py
- xastropy/xguis/spec_widgets.py
- xastropy/xguis/utils.py
> FitLLS and more

- xastropy/xguis/spec_guis.py
> Labels, v0.4.1

- xastropy/casbah/CASBAH_galaxy_usage.ipynb
- xastropy/casbah/build_casbah_galaxies.py
- xastropy/obs/radec.py
- xastropy/xguis/igmguesses.py
> MMT targeting

- xastropy/cgm/core.py
- xastropy/cgm/cos_halos.py
- xastropy/igm/abs_sys/ionclms.py
- xastropy/kinematics/absline.py
- xastropy/obs/radec.py
COS Halo and CGM class edits
Kinematic updates and a few other minor edits.
> cos_halos mainly

- xastropy/xguis/IGM_model.json
- xastropy/xguis/igmguesses.py
Tweaks for plotting + enhancements implemented by JXP.
> Igm guesses - tweaks (for plotting mostly)

- xastropy/xguis/xfitllsgui.py
Improved NHI estimation in auto_plls
And made edits to allow auto_plls when a lower z LLS
has already been defined.
> edit to XFitLLS

- xastropy/plotting/simple.py
- xastropy/xguis/utils.py
- xastropy/xutils/xdebug.py
> small change to navigate

- xastropy/obs/finder.py
- xastropy/xutils/peaks.py
Added a not so good peak finder.
Edited the finder program.
> a few minor things

- xastropy/plotting/simple.py
- xastropy/xguis/spec_guis.py
> small edits

- xastropy/igm/abs_sys/lls_utils.py
> moved voigt naming

- docs/examples/AbsSurvey_examples.ipynb
- docs/examples/LLSSurvey_examples.ipynb
- docs/examples/LLSSystem_examples.ipynb
- xastropy/cgm/core.py
- xastropy/igm/__init__.py
- xastropy/igm/abs_sys/__init__.py
- xastropy/igm/abs_sys/abssurvey.py
- xastropy/igm/abs_sys/abssys_utils.py
- xastropy/igm/abs_sys/ionclms.py
- xastropy/igm/abs_sys/lls_utils.py
- xastropy/igm/abs_sys/tests/test_init_abssurvey.py
- xastropy/igm/abs_sys/tests/test_init_llssurvey.py
- xastropy/igm/abs_sys/tests/test_init_llssys.py
- xastropy/igm/abs_sys/tests/test_ionclms.py
- xastropy/igm/abs_sys/tests/test_use_llssys.py
Lots of changes to handle new AbsSystem and AbsComponent
objects in linetools.
> IGM -- Refactoring for AbsSurvey, LLS, and IonClms

- .idea/vcs.xml
- xastropy/xguis/spec_widgets.py
- xastropy/xguis/xfitllsgui.py
> LLS Gui: Refactoring

- xastropy/xguis/spec_widgets.py
- xastropy/xguis/xfitllsgui.py
This fixes a bug with the LLS gui. 
It also allows plotting the zero level and some vertical lines in the spectrum widget, which I like to do for LLS finding. Also increase the width of the spectrum widget for the LLS gui.
> Fixes and tweaks for fitlls gui

- xastropy/xguis/xfitllsgui.py
Now for usage with pyigm
Should be last time. ;)
> guis: Refactoring xfitllsgui again

- xastropy/plotting/bokeh.py
- xastropy/xguis/xfitllsgui.py
> guis: More on XFitLLS GUI

- xastropy/xguis/spec_widgets.py
> xspec: simple fix in spec_widgets

- xastropy/casbah/build_casbah_galaxies.py
- xastropy/casbah/galaxy_data.py
- xastropy/spec/continuum.py
> odds and ends

- xastropy/xguis/spec_widgets.py
> EW in xspec

- xastropy/xguis/igmguesses.py
Added c_mks as global variable in igmguesses.py (increases speed)
> Added c_mks as global variable in igmguesses.py

- xastropy/igm/abs_sys/dla.py
- xastropy/sdss/quasars.py
- xastropy/xguis/igmguesses.py
> guis: IGMGuesses

- xastropy/xguis/igmguesses.py
IGMGuesses: Label displays compatible with matplotlib v1.5.0
> Igm guesses:

- xastropy/xguis/igmguesses.py
> igmguesses: Fixes/Refactoring

- xastropy/xguis/xfitllsgui.py
This makes xfitllsgui work again after the changes in PR #77 
It just moves a bunch of obsolete code back into xfitllsgui.py. That's not ideal, but it works.
> Repair xfitllsgui

- xastropy/xguis/igmguesses.py
fixes related to normalization and logN
This needs a pending linetools PR to work
> IGMGuesses: More fixes

- xastropy/xguis/igmguesses.py
Partially addressing issue #87:
- main docstring help message added
- repair '%' key stroke to select lines
> Igmguesses: ehnancements

- xastropy/xguis/igmguesses.py
> IGMGuesses: Bug fixes

- xastropy/xguis/igmguesses.py
IGMGuesses: patch to deal with nan uncertainty and display residuals.
> IGMGuesses: patch to deal with nan uncertainty and display residuals.

- xastropy/xguis/xfitllsgui.py
> LLS GUI refactored

- xastropy/xguis/igmguesses.py
IGMGuesses: compatibility after linetools' XSpectrum1D refactoring.
> IGMGuesses: compatibility after linetools' XSpectrum1D refactoring.

- xastropy/xguis/xfitllsgui.py
> XFITLLSgui: Some refactoring for XSpectrum1D

- xastropy/xguis/igmguesses.py
IGMGuesses: change the way masking pixels work. Now we only mask out 'bad pixels'. Also added a patch to make the plotting a bit faster.
This partly addresses issue #92
> IGMGuesses: change the way masking pixels work.

- xastropy/xguis/igmguesses.py
> IGMGuesses: Removed Component Class

- xastropy/xguis/igmguesses.py
Igmguesses: changes towards having multiple LineList
> Igmguesses: changes towards having multiple LineList

- xastropy/igm/fN/data.py
- xastropy/plotting/simple.py
- xastropy/xutils/xdebug.py
- xastropy/xutils/xginga.py
New ginga routine for image display
Some other plotting edits too
> Ginga Updated

- xastropy/xguis/igmguesses.py
Speeds up loading files (a lot)
> igmguesses

- xastropy/plotting/simple.py
> Simple plotting

- xastropy/stats/basic.py
> Binomial stats

- xastropy/stats/mcmc.py
- xastropy/xutils/xdebug.py
> ipdb done right

- xastropy/obs/finder.py
> Finder updates

- setup.py
- xastropy/obs/__init__.py
- xastropy/obs/finder.py
- xastropy/obs/keck.py
- xastropy/obs/radec.py
- xastropy/obs/x_getsdssimg.py
- xastropy/plotting/__init__.py
- xastropy/plotting/simple.py
- xastropy/xutils/__init__.py
> Finder updates for Python3
